workflows:
  version: 2
  main:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install deps"
          command: |
            sudo apt-get update -y
            sudo apt-get install -y zip
            sudo npm install -g prettier
      - run:
          name: "prettier test"
          command: |
            find $PWD -type f -name "*.js" | xargs -I {} prettier --check {}
      - run:
          name: "Package Extension"
          command: |
            ./build.sh
      - store_artifacts:
          path: /home/circleci/project/pfcrypto.zip
          destination: /pfcrypto.zip
